In [13]:
import numpy as np
from sklearn import datasets
# from sklearn.datasets load
from sklearn.datasets import load_boston
data = load_boston()

In [64]:
import numpy as np
from sklearn import datasets
data = datasets.load_boston()
# print(data)
X = data.data
Y= data.target
import pandas as pd 
df = pd.DataFrame(X)
df.columns = data.feature_names
df

/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
    dataset. You can load the datasets as follows::

        from sklearn.datasets import fetch_california_housing
        housing = fetch_california_housing()

    for the California housing dataset and::

        from sklearn.datasets import fetch_openml
        housing = fetch_openml(name="house_prices", as_frame=True)

    for the Ames housing dataset.

  warnings.warn(msg, category=FutureWarning)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [72]:
from sklearn import model_selection
X_TRAIN , X_TEST , Y_TRAIN , Y_TEST = model_selection.train_test_split(X,Y, random_state = 42)
from sklearn.linear_model import LinearRegression
alg1 = LinearRegression()
alg1.fit(X_TRAIN , Y_TRAIN)
Y_PRED = alg1.predict(X_TEST)
Y_PRED
print(alg1.score(X_TEST, Y_TEST))
print(alg1.score(X_TRAIN, Y_TRAIN ))

0.6844267283527123
0.7480872598623441

In [83]:
df["age_age"]= df["AGE"] ** 2 
df["rm_rm"] = df["RM"] ** 2
dff = df.values
X2_TRAIN , X2_TEST , Y2_TRAIN , Y2_TEST = model_selection.train_test_split(dff,Y, random_state = 42)
from sklearn.linear_model import LinearRegression
alg2 = LinearRegression()
alg2.fit(X2_TRAIN , Y2_TRAIN)
Y2_PRED = alg2.predict(X2_TEST)

print(alg2.score(X2_TEST, Y2_TEST))
print(alg2.score(X2_TRAIN, Y2_TRAIN ))

0.7779700049597947
0.8077252158661741